
#
# MapServer 8.0 Config File
#
CONFIG

  #
  # Environment variables (see https://mapserver.org/environment_variables.html)
  #
  ENV
    #
    # Limit Mapfile Access
    #
    # MS_MAP_NO_PATH "1"
    MS_MAP_PATTERN "^/etc/mapserver" ## required

    #
    # Global Log/Debug Setup
    #
    # MS_DEBUGLEVEL "5"
     MS_ERRORFILE stderr

    #
    # Default Map
    #
     MS_MAPFILE "/etc/mapserver/maps/default.map"

    #
    # Proj Library
    #
    # PROJ_DATA "/usr/local/share/proj/"

    #
    # Request Control
    #
    # disable POST requests (allowed by default, any value will do)
    # MS_NO_POST "1"

    #
    # Other Options
    #
    # MS_ENCRYPTION_KEY
    # MS_USE_GLOBAL_FT_CACHE
    # MS_PDF_CREATION_DATE
    # MS_MAPFILE_PATTERN "\.map$"
    # MS_XMLMAPFILE_XSLT
    # MS_MODE
    # MS_OPENLAYERS_JS_URL
    # MS_TEMPPATH
    # MS_MAX_OPEN_FILES

    #
    # OGC API
    #
    # OGCAPI_HTML_TEMPLATE_DIRECTORY "/usr/local/share/mapserver/ogcapi/templates/html-bootstrap4/"
  END

  #
  # Map Aliases
  #
  MAPS
    # TEST_MAPFILE "/opt/mapserver/test/test.map"
    inundation "/etc/mapserver/maps/inundation.map"
    hsip "/etc/mapserver/maps/HSIP.map"
    national "/etc/mapserver/maps/NATIONAL.map"
    nid "/etc/mapserver/maps/NID.map"
    political "/etc/mapserver/maps/POLITICAL.map"
    rim "/etc/mapserver/maps/rim.map"
    simdams "/etc/mapserver/maps/simdams.map"
    usace "/etc/mapserver/maps/USACE.map"
  END

END
